export const ADD_TO_CART = 'ADD_TO_CART';
export const FETCH_CART_ITEMS = 'FETCH_CART_ITEMS';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCT_DETAILS = 'FETCH_PRODUCT_DETAILS';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
