export const ADD_TO_CART = 'ADD_TO_CART';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCT_DETAILS = 'FETCH_PRODUCT_DETAILS';
export const FETCH_FILTERS_META = 'FETCH_FILTERS_META';
export const SET_FILTERS = 'SET_FILTERS';
export const FETCH_CART_PRODUCTS = 'FETCH_CART_PRODUCTS';
